/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.duoc.proyectorrhh.vista;




import cl.duoc.proyectorrhh.controlador.AgregarControlador;
import cl.duoc.proyectorrhh.modelo.Personal;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gustavo Leiva
 */
public class VistaP extends javax.swing.JFrame {

    /**
     * Creates new form VistaP
     */
    public VistaP() {
        initComponents();
        panelAgregar.setVisible(false);
        panelListar.setVisible(false);
        panelEliminar.setVisible(false);
        panelModificar.setVisible(false);
        
        modiNombre.setVisible(false);
        modiPrecio.setVisible(false);
        jComboBox2.setVisible(false);
     
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLayerdPanel = new javax.swing.JLayeredPane();
        panelAgregar = new javax.swing.JPanel();
        lblTitulo1 = new javax.swing.JLabel();
        lblTitulo2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        jtx1 = new javax.swing.JTextField();
        jtx2 = new javax.swing.JTextField();
        lbl5 = new javax.swing.JLabel();
        lbEstado = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jComboBox1 = new javax.swing.JComboBox<>();
        lbl4 = new javax.swing.JLabel();
        jtx4 = new javax.swing.JTextField();
        lbl8 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        lbl6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtx3 = new javax.swing.JTextField();
        lbl7 = new javax.swing.JLabel();
        jtx5 = new javax.swing.JTextField();
        lbl9 = new javax.swing.JLabel();
        jtx8 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jtx9 = new javax.swing.JTextField();
        lbl10 = new javax.swing.JLabel();
        jtx11 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        lbl11 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        lbl112 = new javax.swing.JLabel();
        jtx12 = new javax.swing.JTextField();
        panelListar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnMostrar = new javax.swing.JButton();
        lblTitulo5 = new javax.swing.JLabel();
        lblTitulo3 = new javax.swing.JLabel();
        lblTitulo4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btnBuscar = new javax.swing.JButton();
        lbl12 = new javax.swing.JLabel();
        jtx6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        panelEliminar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jtx10 = new javax.swing.JTextField();
        borrar1 = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        panelModificar = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnModificar = new javax.swing.JButton();
        lblTitulo6 = new javax.swing.JLabel();
        lblTitulo7 = new javax.swing.JLabel();
        lblTitulo8 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        btnBuscar1 = new javax.swing.JButton();
        lbl13 = new javax.swing.JLabel();
        jtx7 = new javax.swing.JTextField();
        lblBusqueda1 = new javax.swing.JLabel();
        lblResultado1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox4 = new javax.swing.JCheckBox();
        modiNombre = new javax.swing.JTextField();
        modiPrecio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        jMenAgregar = new javax.swing.JMenuItem();
        jMenListar = new javax.swing.JMenuItem();
        jMenuEliminar = new javax.swing.JMenuItem();
        JMenuModificar = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca");
        setSize(panelAgregar.getPreferredSize());

        jLayerdPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLayerdPanel.setPreferredSize(new java.awt.Dimension(320, 430));

        panelAgregar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelAgregar.setPreferredSize(new java.awt.Dimension(320, 430));

        lblTitulo1.setText("Administración de Personal");

        lblTitulo2.setText("Proyecto RRHH");

        lbl1.setText("ID:");

        lbl2.setText("rut:");

        lbl3.setText("Nombre:");

        jtx1.setToolTipText("");
        jtx1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtx1.setPreferredSize(new java.awt.Dimension(80, 20));

        jtx2.setMaximumSize(new java.awt.Dimension(150, 20));
        jtx2.setPreferredSize(new java.awt.Dimension(150, 20));
        jtx2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtx2ActionPerformed(evt);
            }
        });

        lbl5.setText("Dirección:");
        lbl5.setToolTipText("");

        lbEstado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbEstado.setText("Estado");
        lbEstado.setMaximumSize(new java.awt.Dimension(80, 14));
        lbEstado.setMinimumSize(new java.awt.Dimension(80, 14));
        lbEstado.setPreferredSize(new java.awt.Dimension(80, 20));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jComboBox1.setMaximumRowCount(20);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "enero", "febrero", "marzo", "abril", "mayo", "junio", "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre" }));
        jComboBox1.setToolTipText("");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        lbl4.setText("Fecha de Ingreso:");

        jtx4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtx4ActionPerformed(evt);
            }
        });

        lbl8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl8.setText("Mes");

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        lbl6.setText("Fecha de Cumpleaños:");

        jLabel11.setText("-");

        jtx3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtx3ActionPerformed(evt);
            }
        });

        lbl7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl7.setText("Día");

        lbl9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl9.setText("Año");

        jtx8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtx8ActionPerformed(evt);
            }
        });

        jLabel15.setText("/");

        jLabel16.setText("/");

        jtx9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtx9ActionPerformed(evt);
            }
        });

        lbl10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl10.setText("Día");

        jLabel18.setText("/");

        lbl11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl11.setText("Mes");

        jComboBox3.setMaximumRowCount(20);
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "enero", "febrero", "marzo", "abril", "mayo", "junio", "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre" }));
        jComboBox3.setToolTipText("");
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        lbl112.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl112.setText("Año");

        jtx12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtx12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAgregarLayout = new javax.swing.GroupLayout(panelAgregar);
        panelAgregar.setLayout(panelAgregarLayout);
        panelAgregarLayout.setHorizontalGroup(
            panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl6)
                .addGap(121, 493, Short.MAX_VALUE))
            .addGroup(panelAgregarLayout.createSequentialGroup()
                .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAgregarLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblTitulo2))
                    .addGroup(panelAgregarLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblTitulo1))
                    .addGroup(panelAgregarLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAgregarLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAgregarLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAgregarLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(btnGuardar)
                        .addGap(10, 10, 10)
                        .addComponent(btnLimpiar)
                        .addGap(10, 10, 10)
                        .addComponent(btnVolver))
                    .addGroup(panelAgregarLayout.createSequentialGroup()
                        .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAgregarLayout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgregarLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl5)
                                    .addComponent(lbl4))
                                .addGap(18, 18, 18)))
                        .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelAgregarLayout.createSequentialGroup()
                                .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtx2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(jtx1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtx3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtx4)
                            .addGroup(panelAgregarLayout.createSequentialGroup()
                                .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lbl7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtx5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(panelAgregarLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jtx8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jtx9)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgregarLayout.createSequentialGroup()
                                .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lbl10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtx11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl11, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox3, 0, 80, Short.MAX_VALUE))
                                .addGap(14, 14, 14)
                                .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl112, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(panelAgregarLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jtx12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelAgregarLayout.setVerticalGroup(
            panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitulo2)
                .addGap(6, 6, 6)
                .addComponent(lblTitulo1)
                .addGap(6, 6, 6)
                .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAgregarLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl1)
                            .addComponent(jtx1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl2)
                            .addComponent(jtx2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jtx3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl3)
                            .addComponent(jtx4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl7)
                            .addComponent(lbl8)
                            .addComponent(lbl9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtx5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtx8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(lbl4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtx9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl5))
                        .addGap(39, 39, 39)
                        .addComponent(lbl6))
                    .addGroup(panelAgregarLayout.createSequentialGroup()
                        .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl10)
                            .addComponent(lbl11)
                            .addComponent(lbl112))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtx11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtx12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))))
                .addGap(25, 25, 25)
                .addComponent(lbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(panelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnVolver)))
        );

        panelListar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelListar.setPreferredSize(new java.awt.Dimension(450, 450));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        lblTitulo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo5.setText("Registro de Empleados");

        lblTitulo3.setText("Proyecto RRHH");

        lblTitulo4.setText("Administración de Personal");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lbl12.setText("rut:");
        lbl12.setToolTipText("");

        jtx6.setToolTipText("");

        jLabel10.setText("-");

        jLabel12.setText("Búsqueda por rut de empleado.");

        jButton1.setText("Limpiar");

        javax.swing.GroupLayout panelListarLayout = new javax.swing.GroupLayout(panelListar);
        panelListar.setLayout(panelListarLayout);
        panelListarLayout.setHorizontalGroup(
            panelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                    .addComponent(lblTitulo5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelListarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(panelListarLayout.createSequentialGroup()
                                .addComponent(lbl12)
                                .addGap(18, 18, 18)
                                .addComponent(jtx6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(jLabel10)
                                .addGap(1, 1, 1)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelListarLayout.createSequentialGroup()
                                .addComponent(btnBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMostrar)))
                        .addGap(27, 27, 27))
                    .addGroup(panelListarLayout.createSequentialGroup()
                        .addGroup(panelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo3)
                            .addComponent(lblTitulo4))
                        .addGap(0, 464, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelListarLayout.setVerticalGroup(
            panelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitulo4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(lblTitulo5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl12)
                    .addComponent(jtx6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnMostrar)
                    .addComponent(jButton1))
                .addGap(58, 58, 58))
        );

        panelEliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("Código: ");

        borrar1.setText("Borrar");
        borrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrar1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Estado");

        javax.swing.GroupLayout panelEliminarLayout = new javax.swing.GroupLayout(panelEliminar);
        panelEliminar.setLayout(panelEliminarLayout);
        panelEliminarLayout.setHorizontalGroup(
            panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEliminarLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(panelEliminarLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jtx10, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(borrar1)))
                .addContainerGap(276, Short.MAX_VALUE))
        );
        panelEliminarLayout.setVerticalGroup(
            panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEliminarLayout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addGroup(panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtx10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrar1))
                .addGap(31, 31, 31)
                .addComponent(jLabel5)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        panelModificar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelModificar.setPreferredSize(new java.awt.Dimension(450, 450));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        lblTitulo6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo6.setText("Registros en Videoteca");

        lblTitulo7.setText("VideoBuster");

        lblTitulo8.setText("Tienda de Películas");

        btnBuscar1.setText("Buscar");
        btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar1ActionPerformed(evt);
            }
        });

        lbl13.setText("Código: ");
        lbl13.setToolTipText("");

        jtx7.setToolTipText("");

        lblBusqueda1.setText("Resultado búsqueda: ");

        lblResultado1.setText("Estado");

        jLabel1.setText("Seleccione los campos que desea modificar");

        jLabel2.setText("Nuevo valor");

        jCheckBox4.setText("Formato 4K");

        modiNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modiNombreActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre");

        jComboBox2.setMaximumRowCount(20);
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Drama", "Comedia", "Romance", "Acción", "Ciencia Ficción", "Fantasía", "Terror", "Musical", "Suspenso", "Bélico", "Melodrama", "Porno", "Animé" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Categoría");

        jLabel7.setText("Precio");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Puede modificar los campos que se carguen abajo con el valor que desee apretando \"Modificar\"");

        jLabel9.setText("Código");

        javax.swing.GroupLayout panelModificarLayout = new javax.swing.GroupLayout(panelModificar);
        panelModificar.setLayout(panelModificarLayout);
        panelModificarLayout.setHorizontalGroup(
            panelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(lblTitulo6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator4)
                    .addGroup(panelModificarLayout.createSequentialGroup()
                        .addComponent(lblResultado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(343, 343, 343))
                    .addGroup(panelModificarLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(panelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelModificarLayout.createSequentialGroup()
                                .addGroup(panelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(panelModificarLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel9)
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabel3)
                                        .addGap(45, 45, 45)
                                        .addComponent(jLabel6)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelModificarLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(modiNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(panelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelModificarLayout.createSequentialGroup()
                                .addComponent(modiPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox4)
                                .addGap(11, 11, 11)
                                .addComponent(btnModificar))
                            .addComponent(jLabel7))
                        .addGap(35, 35, 35))
                    .addGroup(panelModificarLayout.createSequentialGroup()
                        .addComponent(lblBusqueda1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtx7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar1))
                    .addGroup(panelModificarLayout.createSequentialGroup()
                        .addGroup(panelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo7)
                            .addComponent(lblTitulo8))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelModificarLayout.setVerticalGroup(
            panelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitulo8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(lblTitulo6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl13)
                        .addComponent(jtx7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar1))
                    .addGroup(panelModificarLayout.createSequentialGroup()
                        .addComponent(lblBusqueda1)
                        .addGap(18, 18, 18)
                        .addComponent(lblResultado1)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(11, 11, 11)
                        .addGroup(panelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(3, 3, 3)
                        .addGroup(panelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(modiNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modiPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModificar)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox4))))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jLayerdPanel.setLayer(panelAgregar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayerdPanel.setLayer(panelListar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayerdPanel.setLayer(panelEliminar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayerdPanel.setLayer(panelModificar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayerdPanelLayout = new javax.swing.GroupLayout(jLayerdPanel);
        jLayerdPanel.setLayout(jLayerdPanelLayout);
        jLayerdPanelLayout.setHorizontalGroup(
            jLayerdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelListar, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
            .addGroup(jLayerdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE))
            .addGroup(jLayerdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayerdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayerdPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jLayerdPanelLayout.setVerticalGroup(
            jLayerdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelListar, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
            .addGroup(jLayerdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelAgregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE))
            .addGroup(jLayerdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayerdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayerdPanelLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jMenu.setText("Procesos");

        jMenAgregar.setText("Agregar");
        jMenAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenAgregarActionPerformed(evt);
            }
        });
        jMenu.add(jMenAgregar);

        jMenListar.setText("Listar");
        jMenListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenListarActionPerformed(evt);
            }
        });
        jMenu.add(jMenListar);

        jMenuEliminar.setText("Eliminar");
        jMenuEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEliminarActionPerformed(evt);
            }
        });
        jMenu.add(jMenuEliminar);

        JMenuModificar.setText("Modificar");
        JMenuModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuModificarActionPerformed(evt);
            }
        });
        jMenu.add(JMenuModificar);
        jMenu.add(jSeparator5);

        jMenuSalir.setText("Salir");
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });
        jMenu.add(jMenuSalir);

        jMenuBar1.add(jMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayerdPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayerdPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuSalirActionPerformed

    private void jMenAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenAgregarActionPerformed
        // TODO add your handling code here:
        panelAgregar.setVisible(true);
        panelListar.setVisible(false);
        panelEliminar.setVisible(false);
        panelModificar.setVisible(false);
        lbEstado.setText("Estado");
        jtx1.requestFocus();
    }//GEN-LAST:event_jMenAgregarActionPerformed

    private void jMenListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenListarActionPerformed
        // TODO add your handling code here:
        panelAgregar.setVisible(false);
        panelListar.setVisible(true);
        panelEliminar.setVisible(false);
        panelModificar.setVisible(false);
        
        DefaultTableModel InvActual = new DefaultTableModel();
        jTable1.setModel(InvActual);
        InvActual.addColumn("ID");
        InvActual.addColumn("Nombre");
        InvActual.addColumn("rut");
        InvActual.addColumn("Fecha de Ingreso");
        InvActual.addColumn("Dirección");
        InvActual.addColumn("Fecha de Cumpleaños");
        
        
        Object[] fila = new Object[6];
//        AgregarControlador insertar = new AgregarControlador();
//        Personal  auxil = list.listarPeliculas();
        
//        for(int x =0; x < auxil.size(); ++x){
//            fila[0] = auxil.get(x).getCodigo();
//            fila[1] = auxil.get(x).getNombre();
//            fila[2] = auxil.get(x).getDescripcion();
//            fila[3] = auxil.get(x).getPrecio();
//            fila[4] = auxil.get(x).getFormato4k();
//            InvActual.addRow(fila);
//        }   

    }//GEN-LAST:event_jMenListarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        jtx1.setText("");
        jtx2.setText("");
        jtx4.setText("");
        jComboBox1.setSelectedIndex(0);
        modiNombre.setText("");

        
        
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try{
            Integer id = Integer.parseInt(jtx1.getText());
            Integer rut = Integer.parseInt(jtx2.getText());
            String dv =jtx3.getText();
            String nombre =jtx4.getText();
            Integer dia1 = Integer.parseInt(jtx5.getText());
            String mes1="";
            Integer año1 = Integer.parseInt(jtx8.getText());
            String direccion =jtx9.getText();
            Integer dia2 = Integer.parseInt(jtx11.getText());
            String mes2="";
            Integer año2 = Integer.parseInt(jtx12.getText());
            
            

           switch(jComboBox1.getSelectedIndex()){
                    case 0:
                        mes1 =jComboBox1.getItemAt(0);
                        break;
                    case 1:
                        mes1 =jComboBox1.getItemAt(1);
                        break;
                    case 2:
                        mes1 =jComboBox1.getItemAt(2);
                        break;
                    case 3:
                        mes1 =jComboBox1.getItemAt(3);
                        break;
                    case 4:
                        mes1 =jComboBox1.getItemAt(4);
                        break;
                    case 5:
                        mes1 =jComboBox1.getItemAt(5);
                        break;
                    case 6:
                        mes1 =jComboBox1.getItemAt(6);
                        break;
                    case 7:
                        mes1 =jComboBox1.getItemAt(7);
                        break;
                    case 8:
                        mes1 =jComboBox1.getItemAt(8);
                        break;
                    case 9:
                        mes1 =jComboBox1.getItemAt(9);
                        break;
                    case 10:
                        mes1 =jComboBox1.getItemAt(10);
                        break;
                    case 11:
                        mes1 =jComboBox1.getItemAt(11);
                        break;
            }   
           
           switch(jComboBox3.getSelectedIndex()){
                    case 0:
                        mes2 =jComboBox3.getItemAt(0);
                        break;
                    case 1:
                        mes2 =jComboBox3.getItemAt(1);
                        break;
                    case 2:
                        mes2 =jComboBox3.getItemAt(2);
                        break;
                    case 3:
                        mes2 =jComboBox3.getItemAt(3);
                        break;
                    case 4:
                        mes2 =jComboBox3.getItemAt(4);
                        break;
                    case 5:
                        mes2 =jComboBox3.getItemAt(5);
                        break;
                    case 6:
                        mes2 =jComboBox3.getItemAt(6);
                        break;
                    case 7:
                        mes2 =jComboBox3.getItemAt(7);
                        break;
                    case 8:
                        mes2 =jComboBox3.getItemAt(8);
                        break;
                    case 9:
                        mes2 =jComboBox3.getItemAt(9);
                        break;
                    case 10:
                        mes2 =jComboBox3.getItemAt(10);
                        break;
                    case 11:
                        mes2 =jComboBox3.getItemAt(11);
                        break;
            }
           
           
          AgregarControlador insertar = new AgregarControlador();
//          Personal  auxil = 
            
//            if (insert.agregarPelicula(codigo,precio,descripcion,formato4k,
//                                   nombre,id_codigo)){
//            
//            JOptionPane.showMessageDialog(null,"La película se ingresó correctamente.");
//            } else {
//                JOptionPane.showMessageDialog(null, "Error. La película ya está existe en el registro "
//                        + "o bien los campos están mal ingresados."
//                    + "\nEl código debe ser entre 10.000 y 99.999."
//                    + "\n El nombre debe ser de 3 caracteres como mínimo."
//                    + "\n El precio tiene que ser mayor que 1.000");
//            }
         
         
        }catch(NumberFormatException ex){
            System.out.println("error de campos");
            JOptionPane.showMessageDialog(null, "Error de campo. Debe ingresar un valor numérico  y una cadena de caracteres donde corresponda");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel InvActual = new DefaultTableModel();
        jTable1.setModel(InvActual);
        InvActual.addColumn("Código");
        InvActual.addColumn("Nombre");
        InvActual.addColumn("Descripcion");
        InvActual.addColumn("Precio");
        InvActual.addColumn("Formato 4K");
        
        Object[] fila = new Object[5];
//        Listar list = new Listar();
//        ArrayList<Pelicula>  auxil = list.listarPeliculas();
        
//        for(int x =0; x < auxil.size(); ++x){
//            fila[0] = auxil.get(x).getCodigo();
//            fila[1] = auxil.get(x).getNombre();
//            fila[2] = auxil.get(x).getDescripcion();
//            fila[3] = auxil.get(x).getPrecio();
//            fila[4] = auxil.get(x).getFormato4k();
//            InvActual.addRow(fila);
//        }
        
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void jMenuEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEliminarActionPerformed
        // TODO add your handling code here:
        panelAgregar.setVisible(false);
        panelListar.setVisible(false);
        panelEliminar.setVisible(true);
        panelModificar.setVisible(false);
        jLabel5.setText("Estado");
    }//GEN-LAST:event_jMenuEliminarActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void borrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrar1ActionPerformed
        // TODO add your handling code here:
        try{
            int codigo =Integer.parseInt(jtx10.getText());
//            Borrar delete = new Borrar();
        
//            if(delete.borrarPelicula(codigo)){
//              jLabel5.setText("La película se ha borrado correctamente.");
//            }else{
//                jLabel5.setText("No se pudo borrar. La película no existe.");
//            }
        }catch(NumberFormatException eev){
            jLabel5.setText("Error. Debe ingresar un valor numérico. No se permiten letras.");
        }
        
    }//GEN-LAST:event_borrar1ActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        try{
        
        int codigo = Integer.parseInt(jtx6.getText());
                
        DefaultTableModel InvActual = new DefaultTableModel();
        jTable1.setModel(InvActual);
        InvActual.addColumn("Código");
        InvActual.addColumn("Nombre");
        InvActual.addColumn("Descripcion");
        InvActual.addColumn("Precio");
        InvActual.addColumn("Formato 4K");
        
        Object[] fila = new Object[5];
//        Listar list = new Listar();
//        Pelicula auxil =list.listarPelicula(codigo);
//        if(auxil.getCodigo()==null){
//            JOptionPane.showMessageDialog(null, "La película no figura en nuestros registros. Digite el valor nuevamente.");
//        }
//        fila[0] = auxil.getCodigo();
//        fila[1] = auxil.getNombre();
//        fila[2] = auxil.getDescripcion();
//        fila[3] = auxil.getPrecio();
//        fila[4] = auxil.getFormato4k();
//        InvActual.addRow(fila);
                 
        }catch(NumberFormatException eev){
        JOptionPane.showMessageDialog(null, "Error de campo. Debe ingresar un valor numérico  donde corresponda");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        panelAgregar.setVisible(false);
        jtx1.setText("");
        jtx2.setText("");
        jtx4.setText("");

    }//GEN-LAST:event_btnVolverActionPerformed

    private void jtx4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtx4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtx4ActionPerformed

    private void jtx2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtx2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtx2ActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        
       try{ 
        String nombre =(modiNombre.getText());
        Integer precio = Integer.parseInt(modiPrecio.getText());
        String formato4k="N";
        if(jCheckBox4.isSelected()){
            formato4k="S";
        }
        
        String descripcion ="";
        Integer id_codigo=0;
                
        switch(jComboBox2.getSelectedIndex()){
                    case 0:
                        descripcion =jComboBox2.getItemAt(0);
                        id_codigo=1;
                        break;
                    case 1:
                        descripcion =jComboBox2.getItemAt(1);
                        id_codigo=2;
                        break;
                    case 2:
                        descripcion =jComboBox2.getItemAt(2);
                        id_codigo=3;
                        break;
                    case 3:
                        descripcion =jComboBox2.getItemAt(3);
                        id_codigo=4;
                        break;
                    case 4:
                        descripcion =jComboBox2.getItemAt(4);
                        id_codigo=5;
                        break;
                    case 5:
                        descripcion =jComboBox2.getItemAt(5);
                        id_codigo=6;
                        break;
                    case 6:
                        descripcion =jComboBox2.getItemAt(6);
                        id_codigo=7;
                        break;
                    case 7:
                        descripcion =jComboBox2.getItemAt(7);
                        id_codigo=8;
                        break;
                    case 8:
                        descripcion =jComboBox2.getItemAt(8);
                        id_codigo=9;
                        break;
                    case 9:
                        descripcion =jComboBox2.getItemAt(9);
                        id_codigo=10;
                        break;
                    case 10:
                        descripcion =jComboBox2.getItemAt(10);
                        id_codigo=11;
                        break;
                    case 11:
                        descripcion =jComboBox2.getItemAt(11);
                        id_codigo=12;
                        break;
                    case 12:
                        descripcion =jComboBox2.getItemAt(12);
                        id_codigo=13;
                        break;
            }
        Integer codigo =Integer.parseInt(jLabel9.getText());
//        Modificar modi = new Modificar();
//        if(
//           modi.modificarPelicula(codigo, precio, descripcion,formato4k,
//                 nombre, id_codigo)){
//            JOptionPane.showMessageDialog(null, "Los campos se modificaron correctamente.");
//            DefaultTableModel InvActual = new DefaultTableModel();
//            jTable2.setModel(InvActual);
//            InvActual.addColumn("Código");
//            InvActual.addColumn("Nombre");
//            InvActual.addColumn("Descripcion");
//            InvActual.addColumn("Precio");
//            InvActual.addColumn("Formato 4K");
//            
//            Object[] fila = new Object[5];
//        Listar list = new Listar();
//        ArrayList<Pelicula>  auxil = list.listarPeliculas();
//        
//        for(int x =0; x < auxil.size(); ++x){
//            fila[0] = auxil.get(x).getCodigo();
//            fila[1] = auxil.get(x).getNombre();
//            fila[2] = auxil.get(x).getDescripcion();
//            fila[3] = auxil.get(x).getPrecio();
//            fila[4] = auxil.get(x).getFormato4k();
//            InvActual.addRow(fila);
//        }   
//        }else {
//            JOptionPane.showMessageDialog(null, "Error.  "
//                        + "Los campos están mal ingresados."
//                    + "\n El nombre debe ser de 3 caracteres como mínimo."
//                    + "\n El precio tiene que ser mayor que 1.000");
//        }
       }catch(NumberFormatException as){
           JOptionPane.showMessageDialog(null, "Error. El campo 'Precio' tiene que ser un valor numérico mayor que 1.000.");
       }
        
       
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed
        // TODO add your handling code here:
//        Pelicula auxil =new Pelicula();
        try{

            int codigo = Integer.parseInt(jtx7.getText());

//            DefaultTableModel InvActual = new DefaultTableModel();
//            jTable2.setModel(InvActual);
//            InvActual.addColumn("Código");
//            InvActual.addColumn("Nombre");
//            InvActual.addColumn("Descripcion");
//            InvActual.addColumn("Precio");
//            InvActual.addColumn("Formato 4K");
//
//            Object[] fila = new Object[5];
//            Listar list = new Listar();
//            auxil =list.listarPelicula(codigo);
//
//            fila[0] = auxil.getCodigo();
//            fila[1] = auxil.getNombre();
//            fila[2] = auxil.getDescripcion();
//            fila[3] = auxil.getPrecio();
//            fila[4] = auxil.getFormato4k();
//            InvActual.addRow(fila);
//            if(auxil.getCodigo()==null){
//                JOptionPane.showMessageDialog(null,"La película no figura en nuestros registros.");
//                btnModificar.setEnabled(false);
//                jLabel1.setVisible(false);
//                jLabel2.setVisible(false);
//                jLabel3.setVisible(false);
//                jLabel6.setVisible(false);
//                jLabel7.setVisible(false);
//                jLabel9.setVisible(false);
//                modiNombre.setVisible(false);
//                modiNombre.setText("");
//                modiPrecio.setVisible(false);
//                modiPrecio.setText("");
//                jCheckBox4.setVisible(false);
//                jComboBox2.setVisible(false);
//            }
        }catch(NumberFormatException eev){
            JOptionPane.showMessageDialog(null, "Error de campo. Debe ingresar un valor numérico  donde corresponda");
        }
        

        
//       if(auxil.getCodigo()!=null){ 
//        modiNombre.setText(auxil.getNombre());
//        modiPrecio.setText(auxil.getPrecio().toString());
//        
//        btnModificar.setEnabled(true);
//        jLabel1.setVisible(true);
//        jLabel2.setVisible(true);
//        jLabel3.setVisible(true);
//        jLabel6.setVisible(true);
//        jLabel7.setVisible(true);
//        jLabel9.setVisible(true);
//        
//        jCheckBox4.setVisible(true);
//        modiNombre.setVisible(true);
//        modiPrecio.setVisible(true);
//        jComboBox2.setVisible(true);
//        
//        if(auxil.getFormato4k().toLowerCase().equals("s")){
//            jCheckBox4.setSelected(true);
//        }
//        jLabel9.setText(auxil.getCodigo().toString());
//        jComboBox2.setSelectedItem(auxil.getDescripcion());
//                        
//       }
        

    }//GEN-LAST:event_btnBuscar1ActionPerformed

    private void modiNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modiNombreActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_modiNombreActionPerformed

    private void JMenuModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuModificarActionPerformed
        // TODO add your handling code here:
        panelAgregar.setVisible(false);
        panelListar.setVisible(false);
        panelEliminar.setVisible(false);
        panelModificar.setVisible(true);
        btnModificar.setEnabled(false);
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel9.setVisible(false);
        
        
        modiNombre.setVisible(false);
        modiNombre.setText("");
        modiPrecio.setVisible(false);
        modiPrecio.setText("");
        jCheckBox4.setVisible(false);
        jComboBox2.setVisible(false);
        
        DefaultTableModel InvActual = new DefaultTableModel();
            jTable2.setModel(InvActual);
            InvActual.addColumn("Código");
            InvActual.addColumn("Nombre");
            InvActual.addColumn("Descripcion");
            InvActual.addColumn("Precio");
            InvActual.addColumn("Formato 4K");
            
            Object[] fila = new Object[5];
//        Listar list = new Listar();
//        ArrayList<Pelicula>  auxil = list.listarPeliculas();
//        
//        for(int x =0; x < auxil.size(); ++x){
//            fila[0] = auxil.get(x).getCodigo();
//            fila[1] = auxil.get(x).getNombre();
//            fila[2] = auxil.get(x).getDescripcion();
//            fila[3] = auxil.get(x).getPrecio();
//            fila[4] = auxil.get(x).getFormato4k();
//            InvActual.addRow(fila);
//        }   



    }//GEN-LAST:event_JMenuModificarActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jtx3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtx3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtx3ActionPerformed

    private void jtx8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtx8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtx8ActionPerformed

    private void jtx9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtx9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtx9ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jtx12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtx12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtx12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMenuModificar;
    private javax.swing.JToggleButton borrar1;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnBuscar1;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnLimpiar;
    public javax.swing.JButton btnModificar;
    public javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnVolver;
    public javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox4;
    public javax.swing.JComboBox<String> jComboBox1;
    public javax.swing.JComboBox<String> jComboBox2;
    public javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayerdPanel;
    public javax.swing.JMenuItem jMenAgregar;
    public javax.swing.JMenuItem jMenListar;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMenuEliminar;
    public javax.swing.JMenuItem jMenuSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    public javax.swing.JTable jTable1;
    public javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jtx1;
    private javax.swing.JTextField jtx10;
    private javax.swing.JTextField jtx11;
    private javax.swing.JTextField jtx12;
    public javax.swing.JTextField jtx2;
    private javax.swing.JTextField jtx3;
    private javax.swing.JTextField jtx4;
    private javax.swing.JTextField jtx5;
    public javax.swing.JTextField jtx6;
    public javax.swing.JTextField jtx7;
    private javax.swing.JTextField jtx8;
    private javax.swing.JTextField jtx9;
    public javax.swing.JLabel lbEstado;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl11;
    private javax.swing.JLabel lbl112;
    private javax.swing.JLabel lbl12;
    private javax.swing.JLabel lbl13;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    private javax.swing.JLabel lblBusqueda1;
    public javax.swing.JLabel lblResultado1;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JLabel lblTitulo3;
    private javax.swing.JLabel lblTitulo4;
    private javax.swing.JLabel lblTitulo5;
    private javax.swing.JLabel lblTitulo6;
    private javax.swing.JLabel lblTitulo7;
    private javax.swing.JLabel lblTitulo8;
    private javax.swing.JTextField modiNombre;
    private javax.swing.JTextField modiPrecio;
    public javax.swing.JPanel panelAgregar;
    public javax.swing.JPanel panelEliminar;
    public javax.swing.JPanel panelListar;
    public javax.swing.JPanel panelModificar;
    // End of variables declaration//GEN-END:variables
}
